### PR TITLE
V1.3: Post v1.2 refactoring

### LINKED ISSUE #105: EMERGENCY: Refactor Add/Edit Command, and other necessary classes
**Issues**
- `add` and `edit` commands are implemented very differently (`add` uses the functional pipeline, `edit` uses `EditRecipeDescriptor`)
- Functional pipeline is not used anywhere else in the code outside of the `add` command
- JSON type adapters are not in a separate package
~~- Alphanumeric-only regex is too strict (prevents phrases like "Gluten Free" or "Stir-Fry")~~

### PR DESCRIPTION
**Pull request by filbertphang**
Closes #105 

- [x] Rename `EditRecipeDescriptor` into a generic `RecipeDescriptor`
- [x] Extract `RecipeDescriptor` out of `EditRecipe`
- [x] Refactor `add` command to use `RecipeDescriptor` instead of using functional pipeline
- [x] Add emergency fixes to JsonAdaptedStorage

### CODE REVIEW

**Comment by filbertphang** [comment]
Due to the refactor, do take note that tests regarding add/edit will have to be changed to use the new classes

**Comment by filbertphang** [comment]
Note: JSON Adapters do not implement any kind of `JsonAdapter<T>` interface as we do not need to make use of its polymorphism.

It may be good practice to have the adapters implement this interface to ensure that each adapter implements some basic functionality, however, this has been omitted for now

**Comment by filbertphang** [comment]
Regex refactoring will be moved to a separate PR. See #115 for more info

**Review by SeeuSim — APPROVED** [review]
lgtm

**Pull request merged**
