### PR TITLE
V1.4 Bugs UI

### LINKED ISSUE #209: [PE-D][Tester B] Bug in exception handling
Using the same example from the UG, after causing the assertion error (at least that is what I think it is) I try to remove the ingredients, this happens: 

It seems that there is some mistake in exception handling because after I restarted the program, the command(only with noodles) actually works

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Jxleejiaxin/ped#2

### PR DESCRIPTION
**Pull request by JamesLiuZX**
Closes #209 #210  #220  #223  #225  #229 #232 #236 
Task List: (copied from issue):

- [x] Buggy shortcut for deleting recipes #236 

- [x] Can't paste from clipboard using CTRL + V in add recipe form #220 (please check for bug vs new feature)

- [x] Edit item window shows wrong ingredient input format #225 #223 #232 

- [x] Mouse hover takes priority over cardpane keyboard selector #229 #210 

- [x] Bug in exception handling #209 (refer to [this](https://github.com/AY2223S2-CS2103T-T13-2/tp/issues/209#issuecomment-1494736764) link for discussion)

### CODE REVIEW

**Comment by filbertphang** [comment]
- **fix for #236:** doesn't work on my end. even though no recipe card is selected (and highlighted in blue), pressing the "delete" key still prompts me to delete. if i confirm the deletion, the first recipe in the list is deleted
- **fix for #220:** verified working
- **fix for #225 and duplicates**: edit form ingredients still use `a/`, and add form ingredients are still empty. looking at the commit history, it looks like commit 9cdbdf9 is named wrongly? you may want to investigate

**Comment by JamesLiuZX** [comment]
> * **fix for [[PE-D][Tester D] Buggy shortcut for deleting recipes #236](https://github.com/AY2223S2-CS2103T-T13-2/tp/issues/236):** doesn't work on my end. even though no recipe card is selected (and highlighted in blue), pressing the "delete" key still prompts me to delete. if i confirm the deletion, the first recipe in the list is deleted
> * **fix for [[PE-D][Tester E] Can't paste from clipboard using CTRL + V in add recipe form #220](https://github.com/AY2223S2-CS2103T-T13-2/tp/issues/220):** verified working
> * **fix for [[PE-D][Tester B] Edit item window shows wrong ingredient input format #225](https://github.com/AY2223S2-CS2103T-T13-2/tp/issues/225) and duplicates**: edit form ingredients still use `a/`, and add form ingredients are still empty. looking at the commit history, it looks like commit [9cdbdf9](https://github.com/AY2223S2-CS2103T-T13-2/tp/commit/9cdbdf965eabf6cc71f7a283fae9917ca120f7e3) is named wrongly? you may want to investigate

Thanks. 3rd point is fixed. Could you test again for point 1? Right now on a fresh launch pressing 'D' does not trigger delete, unless the cursor is hovering over the card.

**Comment by SeeuSim** [comment]
codecov for UI patches may be ignored

**Review by filbertphang — COMMENTED** [review]
all fixes are verified to be working, except for pre-filled text for add form. 
for the add form, pre-filled text for ingredient and step fields are still not present (although they work for the edit form)
image

**Comment by SeeuSim** [comment]
Is this go for merge?

**Comment by SeeuSim** [comment]
> all fixes are verified to be working, except for pre-filled text for add form.
> for the add form, pre-filled text for ingredient and step fields are still not present (although they work for the edit form)
> image

For this, since step and ingredient share the same textField, the prompt text has to be added via CSS @JamesLiuZX

**Review by SeeuSim — APPROVED** [review]
Thanks for the fix - looks good to me :)

**Pull request merged**
