### PR TITLE
V1.2: Refactor UI + Add Recipe Popup

### PR DESCRIPTION
**Pull request by JamesLiuZX**

### CODE REVIEW

**Comment by SeeuSim** [comment]
Add some screengrabs to demo

**Comment by JamesLiuZX** [comment]
> Add some screengrabs to demo

Added

**Review by SeeuSim — APPROVED** [review]
lgtm

**Review by ZHTang29 — APPROVED** [review]
LGTM, good work

**Review by filbertphang — APPROVED** [review]

**Pull request merged**
